[workspace]

members = [
    "apps/cloud",
    "apps/keck",
    "libs/jwst",
    "libs/jwst-binding/jwst-ffi",
    "libs/jwst-binding/jwst-jni",
    # "libs/jwst-binding/jwst-py",
    # "libs/jwst-binding/jwst-wasm",
    "libs/jwst-logger",
    "libs/jwst-storage",
    "libs/jwst-storage/src/docs/migration",
    "libs/OctoBase",
    "libs/vendors/cang-jie",
    "libs/vendors/y-sync-0.14",
    "libs/vendors/y-crdt-0.14/yrs",
    "libs/vendors/y-crdt-0.14/lib0",
]

exclude = [
    "libs/vendors/y-crdt/yrs",
    "libs/vendors/y-crdt/lib0",
    "libs/vendors/y-sync",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
